import * as stylex from "@stylexjs/stylex"

import { breakpoints, colors, fonts } from "./tokens.stylex"

const fadeIn = stylex.keyframes({
  "0%": { opacity: 0 },
  "40%": { opacity: 0.6 },
  "60%": { opacity: 0.8 },
  "100%": { opacity: 1 },
})

export const styles = stylex.create({
  box: {
    boxSizing: "border-box",
  },
  html: {
    boxSizing: "border-box",
    scrollBehavior: "smooth",
    minWidth: 0,
    width: "100%",
    maxWidth: "100%",
    minHeight: "100svh",
    backgroundColor: colors.page,
    overscrollBehaviorX: "auto",
    overscrollBehaviorY: "auto",
    "::selection": {
      backgroundColor: colors.selection,
      color: colors.text,
      textShadow: "none",
    },
  },
  body: {
    boxSizing: "border-box",
    margin: 0,
    textRendering: "optimizeLegibility",
    minHeight: "100svh",
    width: "100%",
    maxWidth: "100%",
    backgroundColor: colors.page,
    color: colors.text,
    fontFamily: fonts.sans,
    WebkitFontSmoothing: "antialiased",
    MozOsxFontSmoothing: "grayscale",
    transitionProperty: "background-color, color, border-color",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
    overscrollBehaviorX: "auto",
    overscrollBehaviorY: "auto",
  },
  shell: {
    boxSizing: "border-box",
    marginInline: "auto",
    display: "flex",
    minHeight: "100svh",
    width: "100%",
    maxWidth: "56rem",
    minWidth: 0,
    flexDirection: "column",
    backgroundColor: colors.page,
    color: colors.text,
    paddingBottom: "max(2rem, env(safe-area-inset-bottom, 0px))",
  },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },

  homeMain: {
    boxSizing: "border-box",
    marginInline: "auto",
    display: "flex",
    width: "100%",
    minWidth: 0,
    maxWidth: "56rem",
    flexGrow: 1,
    flexDirection: "column",
    paddingInline: {
      default: 24,
      [breakpoints.sm]: 40,
      [breakpoints.lg]: 48,
    },
    paddingTop: {
      default: 48,
      [breakpoints.sm]: 128,
    },
  },
  homeHeader: {
    boxSizing: "border-box",
    marginBottom: {
      default: 32,
      [breakpoints.sm]: 24,
    },
    minWidth: 0,
  },
  homeTitle: {
    margin: 0,
    padding: 0,
    fontSize: {
      default: "1.125rem",
      [breakpoints.sm]: "1.25rem",
    },
    fontWeight: 500,
    lineHeight: 1.3,
  },
  workLink: {
    color: "inherit",
    textDecorationLine: "none",
    cursor: "pointer",
  },
  nameWrap: {
    position: "relative",
    display: "block",
    overflow: "hidden",
  },
  nameCurrent: {
    display: "inline-block",
    transitionProperty: "transform",
    transitionDuration: "0.3s",
    transitionTimingFunction: "ease-in-out",
    transform: {
      default: "translateY(0)",
      [stylex.when.ancestor(":hover")]: "translateY(-100%)",
    },
  },
  nameAlt: {
    position: "absolute",
    left: 0,
    top: 0,
    display: "inline-block",
    transitionProperty: "transform",
    transitionDuration: "0.3s",
    transitionTimingFunction: "ease-in-out",
    transform: {
      default: "translateY(100%)",
      [stylex.when.ancestor(":hover")]: "translateY(0)",
    },
  },
  homeCopy: {
    boxSizing: "border-box",
    minWidth: 0,
    width: "100%",
  },
  homeP: {
    fontSize: "1rem",
    lineHeight: 1.625,
    color: colors.text,
  },
  homePSpaced: {
    marginTop: 16,
    fontSize: "1rem",
    lineHeight: 1.625,
    color: colors.text,
  },
  homeLead: {
    marginTop: 32,
    fontSize: "1rem",
    fontWeight: 500,
    lineHeight: 1.5,
    color: colors.text,
  },
  homeList: {
    marginTop: 8,
    paddingLeft: 20,
    listStyleType: "disc",
    fontSize: "1rem",
    lineHeight: 1.5,
    color: colors.text,
  },
  homeListItem: {
    marginTop: {
      default: 4,
      ":first-child": 0,
    },
  },
  homeWritings: {
    boxSizing: "border-box",
    marginTop: 20,
    minWidth: 0,
    width: "100%",
  },
  homeWritingsTitle: {
    fontSize: "1rem",
    fontWeight: 500,
    lineHeight: 1.5,
    color: colors.text,
  },
  homeWritingsList: {
    marginTop: 8,
    paddingLeft: 20,
    listStyleType: "decimal",
    color: colors.text,
  },
  homeWritingsItem: {
    paddingLeft: 4,
    fontSize: "1rem",
    lineHeight: 1.5,
    marginTop: {
      default: 4,
      ":first-child": 0,
    },
  },
  homeFooter: {
    marginTop: 24,
    fontSize: "1rem",
    lineHeight: 1.5,
    color: colors.textMuted,
  },
  homeInlineLink: {
    color: {
      default: colors.homeLink,
      ":hover": colors.homeLink,
    },
    fontWeight: 500,
    textDecorationLine: {
      default: "none",
      ":hover": "underline",
    },
    textDecorationColor: colors.homeLink,
    textDecorationThickness: "0.1em",
    textUnderlineOffset: "0.25rem",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
  },
  homeWritingsLink: {
    color: {
      default: colors.homeLink,
      ":hover": colors.homeLink,
    },
    fontWeight: 500,
    textDecorationLine: {
      default: "none",
      ":hover": "underline",
    },
    textDecorationColor: colors.homeLink,
    textDecorationThickness: "0.1em",
    textUnderlineOffset: "0.25rem",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
  },

  notFound: {
    boxSizing: "border-box",
    display: "flex",
    minHeight: "100svh",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: {
      default: 24,
      [breakpoints.sm]: 40,
    },
  },
  notFoundText: {
    fontSize: "1rem",
  },
  agePage: {
    boxSizing: "border-box",
    display: "flex",
    minHeight: "100svh",
    flexGrow: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: {
      default: 24,
      [breakpoints.sm]: 40,
    },
  },
  ageFade: {
    animationName: fadeIn,
    animationDuration: "0.5s",
    animationTimingFunction: "ease-in-out",
    animationFillMode: "forwards",
    opacity: 0,
    fontFamily: fonts.mono,
    transitionProperty: "color",
    transitionDuration: "0.15s",
  },
  ageValue: {
    fontSize: {
      default: "1.125rem",
      [breakpoints.sm]: "1.5rem",
    },
    color: colors.text,
    fontVariantNumeric: "tabular-nums",
  },

  articleMain: {
    boxSizing: "border-box",
    position: "relative",
    width: "100%",
    minWidth: 0,
    flexGrow: 1,
    fontSize: {
      default: "1.05rem",
      [breakpoints.sm]: 15,
    },
    WebkitTapHighlightColor: "transparent",
  },
  articleInner: {
    boxSizing: "border-box",
    position: "relative",
    marginInline: "auto",
    display: "flex",
    width: "100%",
    maxWidth: "56rem",
    flexDirection: "column",
    gap: 8,
    paddingInline: {
      default: 24,
      [breakpoints.sm]: 40,
      [breakpoints.lg]: 48,
    },
    paddingBottom: 160,
    paddingTop: 128,
  },
  backLink: {
    boxSizing: "border-box",
    display: "inline-flex",
    width: "fit-content",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
    color: {
      default: colors.textSoft,
      ":hover": colors.text,
    },
    textDecorationLine: "none",
    transitionProperty: "color",
    transitionDuration: "0.15s",
  },
  backIcon: {
    width: 16,
    height: 16,
    transitionProperty: "transform",
    transitionDuration: "0.15s",
    transform: {
      default: "translateX(0)",
      [stylex.when.ancestor(":hover")]: "translateX(-4px)",
    },
  },
  articleTitle: {
    scrollMargin: 80,
    fontFamily: fonts.serif,
    fontSize: {
      default: "3.75rem",
      [breakpoints.sm]: "4.5rem",
      [breakpoints.xl]: "6rem",
    },
    fontWeight: 500,
    letterSpacing: "-0.025em",
    color: colors.text,
  },
  articleDesc: {
    marginTop: 16,
    fontSize: "1.125rem",
    lineHeight: 1.625,
    color: colors.textSoft,
  },
  articleDescWithMeta: {
    marginBottom: 6,
  },
  articleDescSolo: {
    marginBottom: 24,
  },
  articleMetaWithDesc: {
    marginBottom: 24,
  },
  articleMetaSolo: {
    marginTop: 16,
    marginBottom: 24,
  },
  articleBody: {
    minWidth: 0,
  },
  writingsStack: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },

  fadeRoot: {
    boxSizing: "border-box",
    pointerEvents: "none",
    userSelect: "none",
  },
  fadeTop: (background: string, stop: string, blur: string) => ({
    backdropFilter: `blur(${blur})`,
    backgroundImage: `linear-gradient(to top, transparent, ${background})`,
    maskImage: `linear-gradient(to bottom, ${background} ${stop}, transparent)`,
  }),
  fadeBottom: (background: string, stop: string, blur: string) => ({
    backdropFilter: `blur(${blur})`,
    backgroundImage: `linear-gradient(to bottom, transparent, ${background})`,
    maskImage: `linear-gradient(to top, ${background} ${stop}, transparent)`,
  }),
  fadeLeft: (background: string, stop: string, blur: string) => ({
    backdropFilter: `blur(${blur})`,
    backgroundImage: `linear-gradient(to left, transparent, ${background})`,
    maskImage: `linear-gradient(to right, ${background} ${stop}, transparent)`,
  }),
  fadeRight: (background: string, stop: string, blur: string) => ({
    backdropFilter: `blur(${blur})`,
    backgroundImage: `linear-gradient(to right, transparent, ${background})`,
    maskImage: `linear-gradient(to left, ${background} ${stop}, transparent)`,
  }),
  fadeOverlayTop: {
    position: "fixed",
    insetInline: 0,
    top: 0,
    zIndex: 10,
    height: 128,
    pointerEvents: "none",
    userSelect: "none",
    backdropFilter: "blur(4px)",
    backgroundImage: `linear-gradient(to top, transparent, ${colors.page})`,
    maskImage: `linear-gradient(to bottom, ${colors.page} 50%, transparent)`,
  },
  fadeOverlayBottom: {
    position: "fixed",
    insetInline: 0,
    bottom: 0,
    zIndex: 10,
    height: "16.666%",
    minHeight: 96,
    pointerEvents: "none",
    userSelect: "none",
    backdropFilter: "blur(4px)",
    backgroundImage: `linear-gradient(to bottom, transparent, ${colors.page})`,
    maskImage: `linear-gradient(to top, ${colors.page} 25%, transparent)`,
  },

  themeToggle: {
    boxSizing: "border-box",
    position: "fixed",
    right: "max(0.5rem, env(safe-area-inset-right, 0px))",
    bottom: "max(0.5rem, env(safe-area-inset-bottom, 0px))",
    zIndex: 100,
    display: "inline-flex",
    width: 36,
    height: 36,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9999,
    borderWidth: 0,
    padding: 0,
    color: colors.text,
    cursor: {
      default: "pointer",
      ":disabled": "not-allowed",
    },
    backgroundColor: {
      default: "transparent",
      ":hover": {
        default: "transparent",
        [breakpoints.hoverFine]: colors.surfaceEmphasis,
      },
      ":active": colors.surfaceMuted,
    },
    transitionProperty: "background-color",
    transitionDuration: "0.15s",
    transitionTimingFunction: "ease",
    outlineWidth: {
      default: 0,
      ":focus-visible": 2,
    },
    outlineStyle: {
      default: "none",
      ":focus-visible": "solid",
    },
    outlineColor: {
      default: "transparent",
      ":focus-visible": colors.accent,
    },
    outlineOffset: {
      default: 0,
      ":focus-visible": 2,
    },
    opacity: {
      default: 1,
      ":disabled": 0.5,
    },
    pointerEvents: {
      default: "auto",
      ":disabled": "none",
    },
  },
  themeIcon: {
    position: "absolute",
    width: 16,
    height: 16,
    transitionProperty: "transform",
    transitionDuration: "0.15s",
  },
  themeIconOn: {
    transform: "scale(1) rotate(0deg)",
  },
  themeIconOff: {
    transform: "scale(0) rotate(90deg)",
  },

  views: {
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    columnGap: 12,
    fontSize: 12,
    color: colors.textSoft,
  },
  viewsItem: {
    display: "flex",
    alignItems: "center",
  },
  viewsIcon: {
    width: 12,
    height: 12,
    marginRight: 6,
  },

  tocWrap: {
    position: "relative",
  },
  tocList: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    fontSize: 14,
    margin: 0,
    padding: 0,
    listStyleType: "none",
  },
  tocDot: (top: number, left: number) => ({
    pointerEvents: "none",
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 9999,
    backgroundColor: colors.tocActive,
    transitionProperty: "top, left",
    transitionDuration: "0.3s",
    transitionTimingFunction: "ease-out",
    top,
    left,
    transform: "translateY(-50%)",
  }),
  tocItem: (paddingLeft: number) => ({
    position: "relative",
    paddingLeft,
  }),
  tocLink: {
    display: "block",
    textDecorationLine: "none",
    transitionProperty: "color",
    transitionDuration: "0.2s",
  },
  tocLinkSidebar: {
    paddingBlock: 6,
  },
  tocLinkAccordion: {
    paddingBlock: 2,
    lineHeight: 1.375,
  },
  tocLinkActive: {
    fontWeight: 500,
    color: colors.tocActive,
  },
  tocLinkIdle: {
    color: {
      default: colors.textSoft,
      ":hover": colors.text,
    },
  },
  tocMobile: {
    boxSizing: "border-box",
    marginBottom: 40,
    overflow: "hidden",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    display: {
      default: "block",
      [breakpoints.xl2]: "none",
    },
  },
  tocMobileHead: {
    boxSizing: "border-box",
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingInline: 16,
    paddingBlock: 12,
    textAlign: "left",
    fontSize: 14,
    color: colors.textSoft,
  },
  tocMobileBtn: {
    boxSizing: "border-box",
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingInline: 16,
    paddingBlock: 12,
    textAlign: "left",
    fontSize: 14,
    color: {
      default: colors.textSoft,
      ":hover": colors.text,
    },
    cursor: "pointer",
    backgroundColor: "transparent",
    borderWidth: 0,
    transitionProperty: "color",
    transitionDuration: "0.15s",
  },
  tocLabel: {
    fontWeight: 500,
  },
  tocChevron: {
    width: 16,
    height: 16,
    flexShrink: 0,
    transitionProperty: "transform",
    transitionDuration: "0.2s",
  },
  tocChevronOpen: {
    transform: "rotate(180deg)",
  },
  tocSidebar: {
    pointerEvents: "none",
    position: "fixed",
    left: 32,
    top: 128,
    zIndex: 20,
    width: 256,
    display: {
      default: "none",
      [breakpoints.xl2]: "block",
    },
  },
  tocNav: {
    boxSizing: "border-box",
    pointerEvents: "auto",
    maxHeight: "calc(100vh - 10rem)",
    overflowY: "auto",
    paddingRight: 8,
    scrollbarWidth: "thin",
    scrollbarColor: colors.scrollbarPair,
    "::-webkit-scrollbar": {
      width: 6,
    },
    "::-webkit-scrollbar-track": {
      backgroundColor: colors.scrollbarTrack,
      borderRadius: 3,
    },
    "::-webkit-scrollbar-thumb": {
      backgroundColor: colors.scrollbarThumb,
      borderRadius: 3,
    },
  },
  tocAccordionBody: {
    boxSizing: "border-box",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    paddingInline: 4,
    paddingBlock: 20,
  },

  previewLink: {
    fontWeight: 500,
    textDecorationLine: "underline",
    textUnderlineOffset: 4,
    textDecorationColor: colors.linkDecoration,
  },
  previewCard: {
    boxSizing: "border-box",
    zIndex: 50,
    width: 320,
    overflow: "hidden",
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 0,
    color: colors.text,
    boxShadow:
      "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    outline: "none",
  },
  previewImageWrap: {
    boxSizing: "border-box",
    position: "relative",
    height: 160,
    width: "100%",
    overflow: "hidden",
    backgroundColor: colors.surfaceMuted,
  },
  previewImage: {
    height: "100%",
    width: "100%",
    objectFit: "cover",
  },
  previewBody: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 12,
  },
  previewMeta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    color: colors.textSoft,
  },
  previewFavicon: {
    borderRadius: 2,
  },
  previewDomain: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  previewExt: {
    marginLeft: "auto",
    width: 12,
    height: 12,
    flexShrink: 0,
    opacity: 0.5,
  },
  previewTitle: {
    overflow: "hidden",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: 1.375,
    color: colors.text,
  },
  previewDesc: {
    overflow: "hidden",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    fontSize: 12,
    lineHeight: 1.625,
    color: colors.textMuted,
  },

  mermaidWrap: {
    boxSizing: "border-box",
    marginBlock: 24,
    width: "100%",
    minWidth: 0,
    maxWidth: "100%",
  },
  mermaidScroll: {
    boxSizing: "border-box",
    maxHeight: "min(70vh, 48rem)",
    width: "100%",
    minWidth: 0,
    overflow: "auto",
    WebkitOverflowScrolling: "touch",
    paddingBlock: 12,
    paddingInline: {
      default: 12,
      [breakpoints.sm]: 20,
    },
    scrollbarWidth: "thin",
    scrollbarColor: colors.scrollbarPairClear,
    "::-webkit-scrollbar": {
      width: 8,
      height: 8,
    },
    "::-webkit-scrollbar-thumb": {
      backgroundColor: colors.scrollbarThumb,
      borderRadius: 4,
    },
    "::-webkit-scrollbar-track": {
      backgroundColor: "transparent",
    },
  },
  mermaidBox: {
    boxSizing: "border-box",
    width: "100%",
    minWidth: 0,
    padding: {
      default: 8,
      [breakpoints.sm]: 12,
    },
    backgroundColor: colors.surface,
    color: colors.text,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 12,
  },

  mdxH1: {
    marginTop: 8,
    scrollMargin: 112,
    fontFamily: fonts.sans,
    fontSize: "1.875rem",
    fontWeight: 500,
    letterSpacing: "-0.025em",
    color: colors.text,
    textWrap: "balance",
  },
  mdxH2: {
    marginTop: {
      default: 64,
      ":first-child": 0,
      [breakpoints.lg]: 32,
    },
    scrollMargin: 112,
    fontFamily: fonts.sans,
    fontSize: "1.25rem",
    fontWeight: 500,
    letterSpacing: "-0.025em",
    color: colors.text,
    textWrap: "balance",
  },
  mdxH3: {
    marginTop: 48,
    scrollMargin: 112,
    fontFamily: fonts.sans,
    fontSize: "1.125rem",
    fontWeight: 500,
    letterSpacing: "-0.025em",
    color: colors.text,
    textWrap: "balance",
  },
  mdxH4: {
    marginTop: 32,
    scrollMargin: 112,
    fontFamily: fonts.sans,
    fontSize: "1rem",
    fontWeight: 500,
    letterSpacing: "-0.025em",
    color: colors.text,
    textWrap: "balance",
  },
  mdxP: {
    fontSize: "1.125rem",
    lineHeight: 1.625,
    color: colors.text,
    marginTop: {
      default: 8,
      ":first-child": 0,
    },
  },
  mdxOl: {
    marginBottom: 8,
    marginLeft: 24,
    marginTop: 0,
    listStyleType: "decimal",
    fontSize: "1.125rem",
    color: colors.text,
  },
  mdxUl: {
    marginBottom: 8,
    marginLeft: 24,
    marginTop: 0,
    listStyleType: "disc",
    fontSize: "1.125rem",
    color: colors.text,
  },
  mdxLi: {
    marginTop: 8,
    paddingLeft: 8,
    fontSize: "1.125rem",
    color: colors.text,
  },
  mdxEm: {
    fontWeight: 500,
    fontStyle: "italic",
  },
  mdxStrong: {
    fontWeight: 500,
  },
  mdxLink: {
    fontWeight: 500,
    color: {
      default: colors.text,
      ":hover": colors.text,
    },
    opacity: {
      default: 1,
      ":hover": 0.9,
    },
    textDecorationLine: "underline",
    textUnderlineOffset: 4,
    textDecorationColor: colors.linkDecoration,
    transitionProperty: "opacity",
    transitionDuration: "0.15s",
  },
  mdxCode: {
    fontFamily: fonts.mono,
    fontSize: "0.9em",
    fontWeight: 500,
    paddingInline: "0.4em",
    paddingBlock: "0.2em",
    borderRadius: "0.3em",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.codeBorder,
    backgroundColor: colors.codeBg,
    color: colors.text,
  },
  mdxCodeInPre: {
    fontFamily: fonts.mono,
    fontSize: 12,
    fontWeight: 500,
    lineHeight: 1.5,
    padding: 0,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    color: colors.preText,
  },
  mdxPre: {
    boxSizing: "border-box",
    backgroundColor: colors.preBg,
    color: colors.preText,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.preBorder,
    borderRadius: 8,
    overflowX: "auto",
    padding: 16,
    marginBlock: 24,
    lineHeight: 1,
    scrollbarWidth: "none",
    "::-webkit-scrollbar": {
      display: "none",
    },
  },
  mdxTableWrap: {
    boxSizing: "border-box",
    marginBlock: 24,
    width: "100%",
    overflowX: "auto",
  },
  mdxTable: {
    display: "table",
    position: "relative",
    width: "100%",
    maxWidth: "100%",
    fontSize: 14,
    color: colors.text,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderCollapse: "collapse",
  },
  mdxTh: {
    paddingBlock: 12,
    paddingInline: 16,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    color: colors.text,
    textAlign: "left",
    verticalAlign: "top",
    backgroundColor: colors.surfaceMuted,
    whiteSpace: "normal",
    wordBreak: "break-word",
  },
  mdxTd: {
    paddingBlock: 12,
    paddingInline: 16,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    color: colors.text,
    textAlign: "left",
    verticalAlign: "top",
    whiteSpace: "normal",
    wordBreak: "break-word",
  },
  mdxTdLast: {
    borderBottomWidth: 0,
  },
  mdxCellEnd: {
    textAlign: "right",
  },
  mdxQuote: {
    marginTop: 24,
    borderLeftWidth: 2,
    borderLeftStyle: "solid",
    borderLeftColor: colors.borderStrong,
    paddingLeft: 24,
    fontSize: "1.125rem",
    fontStyle: "italic",
    color: colors.textMuted,
  },
  mdxHr: {
    borderColor: colors.border,
    color: colors.border,
  },
})
